### ISSUE TITLE
Error en MainFormData.cs 

### ISSUE THREAD

**Issue by barahona2684** [TheMagician1/redmine-desktop-client#60]
**El tipo 'T' no se puede usar como parámetro de tipo 'T' en el tipo o método genérico 'Redmine.Net.Api.Types.Identifiable<T>'. No hay ninguna conversión de referencia implícita de 'T' a 'System.IEquatable<T>'. (CS0311) - (...)\redmine-desktop-client\Redmine.Client\MainFormData.cs:268,37**

```
        public static Dictionary<int, T> ToDictionaryId<T>(IList<T> list) where T : Identifiable<T>
        {
            Dictionary<int, T> dict = new Dictionary<int,T>();
            foreach (T element in list)
            {
                dict.Add(element.Id, element);
            }
            return dict;
        }
```

> SharpDevelop Version : 5.1.0.5216-0e58df71
> .NET Version         : 4.5.51209
> OS Version           : Microsoft Windows NT 6.1.7601 Service Pack 1
> Current culture      : Spanish (Costa Rica) (es-CR)
> Current UI language  : en
> Running under WOW6432, processor architecture: x86-64

**Gracias**

**Comment by Jopie64** [comment]
I just made it compile against an updated Redmine.Api

Can you check whether this fixes your compile error?
(Don't forget to update the Redmine.Api submodule)

**Comment by barahona2684** [comment]
It works perfect, thank you.
